## 中文会有乱码
connor.name: 曾罡
connor.name1: '*'

## YML默认数字是64进制.

## YML 连字符
## propreties 连字符


## 示例代码: Guns
---
---


## false: 使用JDK代理,true使用CGLIB代理
# spring.aop.proxy-target-class: true


## 配置代码提示.TODO
## springBoot的监控特性
## 健康检查,监控,跟踪,环境变量,线程dump


