
##zk
dubbo:
  registry:
    address: zookeeper://192.168.31.18:2181
    timeout: 100000
  protocol:
    name: dubbo
    port: 25585
  scan:
    base-packages: com.connor.taotie
  provider:
    loadbalance:


spring:
  application:
    name: CustomerApp
server:
  port: 8081
